[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web", "--no-typescript", "--dev", "--out-name", "yew-review", "--out-dir", "./static"]

[tasks.serve]
command = "miniserve"
args = ["./static", "--index", "index.html"]